ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma

overrides:
  "@prisma/config>deepmerge-ts": "^8.0.0"
  "prisma>mysql2": "^3.23.1"
